-- Insert numbers 1-100 into basic_learning table
INSERT INTO public.basic_learning (content_type, english_content, gujarati_content, transliteration, order_sequence, difficulty_level) VALUES
-- Numbers 1-10 (Difficulty Level 1)
('number', 'One ૧', 'એક', 'ek', 1, 1),
('number', 'Two ૨', 'બે', 'be', 2, 1),
('number', 'Three ૩', 'ત્રણ', 'tran', 3, 1),
('number', 'Four ૪', 'ચાર', 'char', 4, 1),
('number', 'Five ૫', 'પાંચ', 'panch', 5, 1),
('number', 'Six ૬', 'છ', 'chha', 6, 1),
('number', 'Seven ૭', 'સાત', 'sat', 7, 1),
('number', 'Eight ૮', 'આઠ', 'ath', 8, 1),
('number', 'Nine ૯', 'નવ', 'nav', 9, 1),
('number', 'Ten ૧૦', 'દસ', 'das', 10, 1),

-- Numbers 11-50 (Difficulty Level 2)
('number', 'Eleven ૧૧', 'અગિયાર', 'agiyar', 11, 2),
('number', 'Twelve ૧૨', 'બાર', 'bar', 12, 2),
('number', 'Thirteen ૧૩', 'તેર', 'ter', 13, 2),
('number', 'Fourteen ૧૪', 'ચૌદ', 'chaud', 14, 2),
('number', 'Fifteen ૧૫', 'પંદર', 'pandar', 15, 2),
('number', 'Sixteen ૧૬', 'સોળ', 'sol', 16, 2),
('number', 'Seventeen ૧૭', 'સત્તર', 'sattar', 17, 2),
('number', 'Eighteen ૧૮', 'અઢાર', 'adhar', 18, 2),
('number', 'Nineteen ૧૯', 'ઓગણીસ', 'oganis', 19, 2),
('number', 'Twenty ૨૦', 'વીસ', 'vis', 20, 2),
('number', 'Twenty One ૨૧', 'એકવીસ', 'ekvis', 21, 2),
('number', 'Twenty Two ૨૨', 'બાવીસ', 'bavis', 22, 2),
('number', 'Twenty Three ૨૩', 'ત્રેવીસ', 'trevis', 23, 2),
('number', 'Twenty Four ૨૪', 'ચોવીસ', 'chovis', 24, 2),
('number', 'Twenty Five ૨૫', 'પચીસ', 'pachis', 25, 2),
('number', 'Twenty Six ૨૬', 'છવ્વીસ', 'chhavvis', 26, 2),
('number', 'Twenty Seven ૨૭', 'સત્તાવીસ', 'sattavis', 27, 2),
('number', 'Twenty Eight ૨૮', 'અઠ્ઠાવીસ', 'aththavis', 28, 2),
('number', 'Twenty Nine ૨૯', 'ઓગણત્રીસ', 'ogantris', 29, 2),
('number', 'Thirty ૩૦', 'ત્રીસ', 'tris', 30, 2),
('number', 'Thirty One ૩૧', 'એકત્રીસ', 'ektris', 31, 2),
('number', 'Thirty Two ૩૨', 'બત્રીસ', 'batris', 32, 2),
('number', 'Thirty Three ૩૩', 'તેત્રીસ', 'tetris', 33, 2),
('number', 'Thirty Four ૩૪', 'ચોત્રીસ', 'chotris', 34, 2),
('number', 'Thirty Five ૩૫', 'પાંત્રીસ', 'pantris', 35, 2),
('number', 'Thirty Six ૩૬', 'છત્રીસ', 'chhatris', 36, 2),
('number', 'Thirty Seven ૩૭', 'સાડત્રીસ', 'sadtris', 37, 2),
('number', 'Thirty Eight ૩૮', 'અડત્રીસ', 'adtris', 38, 2),
('number', 'Thirty Nine ૩૯', 'ઓગણચાલીસ', 'oganchalis', 39, 2),
('number', 'Forty ૪૦', 'ચાળીસ', 'chalis', 40, 2),
('number', 'Forty One ૪૧', 'એકતાળીસ', 'ektalis', 41, 2),
('number', 'Forty Two ૪૨', 'બેતાળીસ', 'betalis', 42, 2),
('number', 'Forty Three ૪૩', 'તેતાળીસ', 'tetalis', 43, 2),
('number', 'Forty Four ૪૪', 'ચુંતાળીસ', 'chuntalis', 44, 2),
('number', 'Forty Five ૪૫', 'પંતાળીસ', 'pantalis', 45, 2),
('number', 'Forty Six ૪૬', 'છેતાળીસ', 'chhetalis', 46, 2),
('number', 'Forty Seven ૪૭', 'સુડતાળીસ', 'sudtalis', 47, 2),
('number', 'Forty Eight ૪૮', 'અડતાળીસ', 'adtalis', 48, 2),
('number', 'Forty Nine ૪૯', 'ઓગણપચાસ', 'oganpachas', 49, 2),
('number', 'Fifty ૫૦', 'પચાસ', 'pachas', 50, 2),

-- Numbers 51-100 (Difficulty Level 3)
('number', 'Fifty One ૫૧', 'એકાવન', 'ekavan', 51, 3),
('number', 'Fifty Two ૫૨', 'બાવન', 'bavan', 52, 3),
('number', 'Fifty Three ૫૩', 'ત્રેપન', 'trepan', 53, 3),
('number', 'Fifty Four ૫૪', 'ચોપન', 'chopan', 54, 3),
('number', 'Fifty Five ૫૫', 'પચપન', 'pachpan', 55, 3),
('number', 'Fifty Six ૫૬', 'છપન', 'chhapan', 56, 3),
('number', 'Fifty Seven ૫૭', 'સત્તાવન', 'sattavan', 57, 3),
('number', 'Fifty Eight ૫૮', 'અઠ્ઠાવન', 'aththavan', 58, 3),
('number', 'Fifty Nine ૫૯', 'ઓગણસાઠ', 'ogansath', 59, 3),
('number', 'Sixty ૬૦', 'સાઠ', 'sath', 60, 3),
('number', 'Sixty One ૬૧', 'એકસઠ', 'eksath', 61, 3),
('number', 'Sixty Two ૬૨', 'બાસઠ', 'basath', 62, 3),
('number', 'Sixty Three ૬૩', 'ત્રેસઠ', 'tresath', 63, 3),
('number', 'Sixty Four ૬૪', 'ચોસઠ', 'chosath', 64, 3),
('number', 'Sixty Five ૬૫', 'પાંસઠ', 'pansath', 65, 3),
('number', 'Sixty Six ૬૬', 'છાસઠ', 'chhasath', 66, 3),
('number', 'Sixty Seven ૬૭', 'સડસઠ', 'sadsath', 67, 3),
('number', 'Sixty Eight ૬૮', 'અડસઠ', 'adsath', 68, 3),
('number', 'Sixty Nine ૬૯', 'ઓગણસિત્તેર', 'ogansitter', 69, 3),
('number', 'Seventy ૭૦', 'સિત્તેર', 'sitter', 70, 3),
('number', 'Seventy One ૭૧', 'એકોતર', 'ekotar', 71, 3),
('number', 'Seventy Two ૭૨', 'બોતર', 'botar', 72, 3),
('number', 'Seventy Three ૭૩', 'ત્રોતર', 'trotar', 73, 3),
('number', 'Seventy Four ૭૪', 'ચુોતર', 'chuotar', 74, 3),
('number', 'Seventy Five ૭૫', 'પંચોતર', 'panchotar', 75, 3),
('number', 'Seventy Six ૭૬', 'છોતર', 'chhotar', 76, 3),
('number', 'Seventy Seven ૭૭', 'સિત્યોતર', 'sityotar', 77, 3),
('number', 'Seventy Eight ૭૮', 'અઠોતર', 'athotar', 78, 3),
('number', 'Seventy Nine ૭૯', 'ઓગણએંસી', 'oganansi', 79, 3),
('number', 'Eighty ૮૦', 'એંસી', 'ansi', 80, 3),
('number', 'Eighty One ૮૧', 'એક્યાસી', 'ekyasi', 81, 3),
('number', 'Eighty Two ૮૨', 'બ્યાસી', 'byasi', 82, 3),
('number', 'Eighty Three ૮૩', 'ત્ર્યાસી', 'tryasi', 83, 3),
('number', 'Eighty Four ૮૪', 'ચોર્યાસી', 'choryasi', 84, 3),
('number', 'Eighty Five ૮૫', 'પંચ્યાસી', 'panchyasi', 85, 3),
('number', 'Eighty Six ૮૬', 'છ્યાસી', 'chhyasi', 86, 3),
('number', 'Eighty Seven ૮૭', 'સત્યાસી', 'satyasi', 87, 3),
('number', 'Eighty Eight ૮૮', 'અઠ્યાસી', 'athyasi', 88, 3),
('number', 'Eighty Nine ૮૯', 'ઓગણ્ણેવું', 'ogannevun', 89, 3),
('number', 'Ninety ૯૦', 'નેવું', 'nevun', 90, 3),
('number', 'Ninety One ૯૧', 'એકાણું', 'ekanun', 91, 3),
('number', 'Ninety Two ૯૨', 'બાણું', 'banun', 92, 3),
('number', 'Ninety Three ૯૩', 'ત્રાણું', 'tranun', 93, 3),
('number', 'Ninety Four ૯૪', 'ચોરાણું', 'choranun', 94, 3),
('number', 'Ninety Five ૯૫', 'પંચાણું', 'panchanun', 95, 3),
('number', 'Ninety Six ૯૬', 'છાણું', 'chhanun', 96, 3),
('number', 'Ninety Seven ૯૭', 'સત્તાણું', 'sattanun', 97, 3),
('number', 'Ninety Eight ૯૮', 'અઠ્ઠાણું', 'aththanun', 98, 3),
('number', 'Ninety Nine ૯૯', 'નવ્વાણું', 'navvanun', 99, 3),
('number', 'One Hundred ૧૦૦', 'સો', 'so', 100, 3);